In [28]:
import pandas as pd

In [29]:
df=pd.read_csv('spam.csv', encoding='ISO-8859-1')

In [34]:
df = df.iloc[:, 0:2]

In [35]:
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham              Will Ì_ b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [37]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [38]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [39]:
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham              Will Ì_ b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

# Now spliting the data into test and train dataset

In [40]:
from sklearn.model_selection import train_test_split


# Here the message is the X and spam is Y

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [42]:
X_train.shape

(4457,)

In [43]:
X_test.shape

(1115,)

In [44]:
X_train[:4]

4533                      I have no money 4 steve mate! !
2102                             Audrie lousy autocorrect
5350        No one interested. May be some business plan.
903     Lovely smell on this bus and it ain't tobacco... 
Name: Message, dtype: object

In [50]:
X_train[0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [51]:
y_train[0]

0

# loading the countvectorizer for Bag of words

In [52]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()


# Here inside the transform when we supply the x train it will generate the BOW for the X train

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7770 sparse matrix of type '<class 'numpy.int64'>'
	with 59472 stored elements in Compressed Sparse Row format>

In [55]:
X_trn_BOW=X_train_cv.toarray() # this is the matrix for the BOW

In [56]:
X_trn_BOW[1]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [57]:
X_trn_BOW.shape # here the output tells us that we have total 7770 words in our BOW and 4457 emails

(4457, 7770)

In [61]:
v.get_feature_names_out()[7000:7700]

array(['toss', 'tot', 'total', 'totally', 'touch', 'touched', 'tough',
       'toughest', 'tour', 'towards', 'town', 'toxic', 'toyota', 'track',
       'trackmarque', 'trade', 'traditions', 'traffic', 'train',
       'trained', 'training', 'trainners', 'trains', 'tram',
       'tranquility', 'transaction', 'transcribing', 'transfer',
       'transfered', 'transferred', 'transfr', 'transfred', 'transport',
       'trash', 'trauma', 'trav', 'travel', 'traveling', 'travelled',
       'travelling', 'treacle', 'treadmill', 'treasure', 'treat',
       'treated', 'treatin', 'treats', 'tree', 'trends', 'tried', 'trip',
       'trips', 'trishul', 'trivia', 'tron', 'trouble', 'troubleshooting',
       'trouser', 'truble', 'true', 'true18', 'truffles', 'truly',
       'truro', 'trust', 'trusting', 'truth', 'try', 'trying', 'ts',
       'tsandcs', 'tscs', 'tscs08714740323', 'tscs087147403231winawk',
       'tsunami', 'tsunamis', 'tt', 'ttyl', 'tues', 'tuesday', 'tui',
       'tuition', 'tul', 'tul

In [62]:
dir(v)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',

In [63]:
v.vocabulary_ 

{'have': 3382,
 'no': 4813,
 'money': 4592,
 'steve': 6479,
 'mate': 4403,
 'audrie': 1155,
 'lousy': 4248,
 'autocorrect': 1165,
 'one': 4959,
 'interested': 3730,
 'may': 4421,
 'be': 1283,
 'some': 6291,
 'business': 1588,
 'plan': 5245,
 'lovely': 4253,
 'smell': 6247,
 'on': 4954,
 'this': 6864,
 'bus': 1585,
 'and': 964,
 'it': 3780,
 'ain': 882,
 'tobacco': 6946,
 'sexy': 6050,
 'cum': 2129,
 'text': 6798,
 'me': 4430,
 'im': 3640,
 'wet': 7478,
 'warm': 7390,
 'ready': 5608,
 'for': 2958,
 'porn': 5328,
 'up': 7187,
 'fun': 3064,
 'msg': 4640,
 'is': 3769,
 'free': 3005,
 'recd': 5628,
 'msgs': 4645,
 '150p': 311,
 'inc': 3668,
 'vat': 7259,
 'cancel': 1653,
 'stop': 6497,
 'haha': 3322,
 'think': 6856,
 'did': 2319,
 'too': 6980,
 'private': 5429,
 'your': 7719,
 '2004': 355,
 'account': 788,
 'statement': 6458,
 '07742676969': 31,
 'shows': 6132,
 '786': 627,
 'unredeemed': 7179,
 'bonus': 1441,
 'points': 5300,
 'to': 6943,
 'claim': 1837,
 'call': 1624,
 '08719180248': 154,

# Now we will train our model

In [66]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)  # here we have trained our model with the BOW of X train and Y train

MultinomialNB()

In [67]:
X_test_cv = v.transform(X_test) # to predict the output on the X_test we will change it into X test BOW

In [68]:
y_pred = model.predict(X_test_cv)  # Now we will make our prediction

In [69]:
y_pred

array([0, 0, 1, ..., 1, 0, 0], dtype=int64)

In [72]:
X_test_cv.toarray()[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [76]:
X_test[583]

'my ex-wife was not able to have kids. Do you want kids one day?'

In [77]:
y_test[583]  # This was the real output of email at index 583

0

In [78]:
y_pred[583] # This is the predicted output of email at index 583

0

# Classification Report

In [81]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       970
           1       0.95      0.92      0.94       145

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [82]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

In [83]:
new_e=v.transform(emails)

In [84]:
y_pred = model.predict(new_e)

In [85]:
y_pred

array([0, 1], dtype=int64)

In [ ]:
# hence the first email is not spam but second email is!!.